### PR TITLE
Exploration and visibility system

### PR DESCRIPTION
**Pull request by JohnathonNow**
Adds a sort of bread crumb system to address #70. Also gives a means to only show things within a certain distance, which could be useful in the future.

Basically it just draws a bunch of white lines within a radius of 5 of the player that persist, to mark where the player has been. 

Right now the distance is hard coded as 5. This should change, either to a constant, or better yet, a new stat. Then, perhaps enemies and items should only render if they are within that distance?

I'm thinking what could happen is:
 - Unseen areas are dim gray 
 - Currently visible areas become bold white
 - Seen areas remain bold gray after they are no longer visible, to track progress.

Any feedback here is welcomed.

### CODE REVIEW

**Comment by a3qz** [comment]
The colors are like weird man

**Comment by a3qz** [comment]
I don't think this works as described? I don't see the color changing back on stuff outside the radius, and boldness doesn't seem to happen

**Comment by JohnathonNow** [comment]
I said that's what could happen. Before it was mostly just breadcrumbs. I just pushed something closer to the proposal.

**Comment by a3qz** [comment]
Can we use COLORS_BLACK | A_BOLD to indicate tiles not currently in range

**Comment by a3qz** [comment]
Enemies in range are also being colored white here, they are not red

**Pull request merged**
